---
language: python
python:
  - 3.5

before_install:
  - echo "Getting docs anonymously"
  - git clone https://github.com/quiltdata/quilt-docs.git
  - cd quilt-docs
  # Ideally monitoring code should be present in master branch,
  # so may be not need to checkout in future
  - git checkout monitor-logs-packages

install:
  - echo "Installing requirements"
  - pip install -U pip
  - pip install -r monitor/requirements.txt

script:
  - echo "Execute monitoring"
  - cd monitor && python3 monitor_pkgs_in_docs.py

notifications:
  email: true
